; PlatformIO Project Configuration File
;
; Simple test firmware to drive all four Maslow 4 DC motors at full speed.
; Target hardware: Maslow 4 (ESP32-S3)

[env:maslow4]
platform = https://github.com/platformio/platform-espressif32.git
framework = arduino
board = esp32-s3-devkitc-1
platform_packages =
    platformio/framework-arduinoespressif32@^3.20016.0
board_build.arduino.upstream_packages = no
build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
monitor_speed = 115200
upload_speed = 921600
